language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ruban' ]; then cd .. && eval "mv $currentfolder generator-ruban" && cd generator-ruban; fi

